<?php

/**
 * User
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class User extends BaseUser
{
	public function setUp()
	{
		$this->actAs( 'Timestampable', array(
				'created' => array( 'name' => 'date_insc' ),
				'updated' => array( 'disabled' => true ),
			) );
	}
	public function preInsert(Doctrine_Event $event)
	{
		$invoker = $event->getInvoker();
		$invoker->pass = md5( $invoker->pass );
	}
}